#!/usr/bin/env bash

CLOJURE_VERSION=1.6.0
URI=http://central.maven.org/maven2/org/clojure/clojure/$CLOJURE_VERSION/clojure-$CLOJURE_VERSION.jar
JAR=clojure-$CLOJURE_VERSION.jar
DOWNLOADS=~/.clojr
JAVA="java"

function oops() {
  echo $@
  exit 1
}

function power_up_java() {
  which java > /dev/null || oops "Can't find java. Please ensure it's installed, and on the path"
}

function download_clojure() {
  if which wget; then
    wget "$URI" -O "$DOWNLOADS/$JAR" --continue
  elif which curl; then
    curl --output "$DOWNLOADS/$JAR" "$URI"
  else
    oops "Please download $URI and save it as $DOWNLOADS/$JAR"
  fi
}

function power_up_clojure() {
  [ -d "$DOWNLOADS" ] || mkdir "$DOWNLOADS"
  [ -f "$DOWNLOADS/$JAR" ] || download_clojure
}

function construct_classpath() {
  local program="$1"
  local root=.
  if [ ! -z "$program" ]; then
    root=$(dirname $1)
  fi
  CLASSPATH=$DOWNLOADS/"$JAR:$root"
}

function rlwrap_java() {
  if which rlwrap > /dev/null && 
    [ "$1" = "-r" -o "$1" = "--repl" -o "$#" = 0 ]; then
    JAVA="rlwrap $JAVA"
  fi
}

power_up_java
power_up_clojure
construct_classpath $1
rlwrap_java

$JAVA -cp $CLASSPATH clojure.main $@
