#!/usr/bin/env bash

cd $(dirname $0)/..

set -e
set -x

VER=$(lein pprint :version | sed s/\"//g)

rm -rf target
lein uberjar
lein pom
mkdir target/dist
cp pom.xml target/dist/
cp target/clojr-$VER-standalone.jar target/dist/clojr-$VER.jar
sed s/VER=REPLACEMENT-TARGET/VER=$VER/ src/clojr > target/dist/clojr
chmod +x target/dist/clojr
