#!/usr/bin/env bash

cd $(dirname $0)/..

set -e
set -x

VER=$(lein pprint :version | sed s/\"//g)

rm -rf target
lein uberjar

# The dist dir is what we want the ~/.clojr dir to look after installation
mkdir target/dist
cp target/clojr-$VER-standalone.jar target/dist/clojr-$VER.jar
sed s/^VER=.*/VER=$VER/ src/clojr > target/dist/clojr
chmod +x target/dist/clojr
