#!/usr/bin/env bash

set -e
set -x

cd $(dirname $0)/..

VER=0.1.0

echo building $VER...
rm -rf target
lein uberjar
mkdir target/dist
cp target/clojr-$VER-standalone.jar target/dist/
sed s/VER=REPLACEMENT-TARGET/VER=$VER/ src/clojr > target/dist/clojr
chmod +x target/dist/clojr
