#!/usr/bin/env bash

set -e 
set -x

cd $(dirname $0)/..

echo installing...
rm -rf ~/.clojr
mkdir -p ~/.clojr
cp target/dist/clojr-*-standalone.jar ~/.clojr/
cp -f target/dist/clojr /usr/local/bin/clojr
