#!/usr/bin/env bash

VER=0.2.0
URI=https://clojars.org/repo/clojr/clojr/$VER/clojr-$VER.jar
DOWNLOADS=~/.clojr
JAR=$DOWNLOADS/clojr-$VER.jar
JAVA=${JAVA:-java}

function oops() {
  echo $@
  exit 1
}

function power_up_java() {
  which java > /dev/null || oops "Can't find java. Please ensure it's installed, and on the path"
}

function download_clojr() {
  mkdir -p $DOWNLOADS
  if which wget; then
    wget "$URI" -O "$JAR" --continue
  elif which curl; then
    curl --output "$JAR" "$URI"
  else
    oops "Please download $URI and save it as $JAR"
  fi
}

function power_up_clojure() {
  [ -f "$JAR" ] || download_clojr
}

function construct_classpath() {
  case $1 in
    -*) CLASSPATH=$JAR;;
    "") CLASSPATH=$JAR:.;;
    *)  CLASSPATH=$JAR:$(dirname $1);;
  esac
}

function rlwrap_java() {
  if which rlwrap > /dev/null &&
    [ "$1" = "-r" -o "$1" = "--repl" -o "$#" = 0 ]; then
    JAVA="rlwrap $JAVA"
  fi
}

power_up_java
power_up_clojure
construct_classpath $1
rlwrap_java


if [ $# = 0 ]; then
  echo "Clojr $VER. (https://github.com/pokle/clojr)"
  echo Powered by Clojure 1.6.0
  $JAVA -cp $CLASSPATH clojure.main -e "(require 'clojr)" -r
else
  $JAVA -cp $CLASSPATH clojure.main -e "(require 'clojr)" "$@"
fi
