#!/usr/bin/env bash

VER=0.1.2
URI=https://clojars.org/repo/clojr/clojr/$VER/clojr-$VER.jar
DOWNLOADS=~/.clojr
JAR=$DOWNLOADS/clojr-$VER.jar
JAVA="java"

function oops() {
  echo $@
  exit 1
}

function power_up_java() {
  which java > /dev/null || oops "Can't find java. Please ensure it's installed, and on the path"
}

function download_clojr() {
  mkdir -p $DOWNLOADS
  if which wget; then
    wget "$URI" -O "$JAR" --continue
  elif which curl; then
    curl --output "$JAR" "$URI"
  else
    oops "Please download $URI and save it as $JAR"
  fi
}

function power_up_clojure() {
  [ -f "$JAR" ] || download_clojr
}

function construct_classpath() {
  local program="$1"
  local root=.
  if [ ! -z "$program" ]; then
    root=$(dirname $program)
  fi
  CLASSPATH="$JAR:$root"
}

function rlwrap_java() {
  if which rlwrap > /dev/null &&
    [ "$1" = "-r" -o "$1" = "--repl" -o "$#" = 0 ]; then
    JAVA="rlwrap $JAVA"
  fi
}

power_up_java
power_up_clojure
construct_classpath $1
rlwrap_java

$JAVA -cp $CLASSPATH clojure.main $@
