#!/usr/bin/env bash

VER=0.6.2
URI=https://repo.clojars.org/clojr/clojr/$VER/clojr-$VER.jar
DOWNLOADS=~/.clojr
JAR="$DOWNLOADS/clojr-$VER.jar"
JAVA=${JAVA:-java}

function oops() {
  echo "$@"
  exit 1
}

function power_up_java() {
  command -v java > /dev/null || oops "Can't find java. Please ensure it's installed, and on the path"
}

function download_clojr() {
  mkdir -p "$DOWNLOADS"
  if command -v curl > /dev/null; then
    curl -fLo "$JAR" "$URI" || oops "Failed to download $URI"
  elif command -v wget > /dev/null; then
    wget "$URI" -O "$JAR" --continue || oops "Failed to download $URI"
  else
    oops "Please download $URI and save it as $JAR"
  fi
}

function power_up_clojure() {
  [ -f "$JAR" ] || download_clojr
}

function construct_classpath() {
  case "$1" in
    -*) CLASSPATH="$JAR";;
    "") CLASSPATH="$JAR:.";;
    *)  CLASSPATH="$JAR:$(dirname "$1")";;
  esac
}

power_up_java
power_up_clojure
construct_classpath "$1"

if [ $# = 0 ]; then
  echo "Clojr $VER - https://github.com/pokle/clojr"
  echo 'Powered by Clojure'
  echo 'HINT: (clojr/dep cheshire "5.13.0" cheshire.core)'
  echo 'Starting Repl-y...'
  exec "$JAVA" -cp "$CLASSPATH" clojure.main -m reply.main -e "(require 'clojr)"
else
  exec "$JAVA" -cp "$CLASSPATH" clojure.main -e "(require 'clojr)" "$@"
fi
